---
type: spine

# Spine switches
spine:
  defaults:
    platform: vEOS-LAB
    bgp_as: 65001
  nodes:
    spine1:
      id: 1
      mgmt_ip: 192.168.0.11/24
    spine2:
      id: 2
      mgmt_ip: 192.168.0.12/24