---
# DC2 specific settings
fabric_name: DC2
bgp_as: 65200

# IP Addressing for DC2
ipv4_underlay:
  p2p_uplinks_ip: 172.32.255.0/24
  loopback_ip: 192.169.255.0/24
  vtep_ip: 192.169.254.0/24

# Inter-DC spine connections (Eth1-2)
spine_interfaces:
  spine3:
    - {interface: Ethernet1, peer: spine4, peer_interface: Ethernet1}
    - {interface: Ethernet2, peer: spine4, peer_interface: Ethernet2}