---
type: spine

# Spine switches
spine:
  defaults:
    platform: vEOS-LAB
    bgp_as: 65002
  nodes:
    spine3:
      id: 1
      mgmt_ip: 192.168.0.13/24
    spine4:
      id: 2
      mgmt_ip: 192.168.0.14/24