---
# Common fabric variables
fabric_name: DUAL_DC_FABRIC

# BGP ASN
bgp_asn: 65100
overlay_loopback_network_summary: 10.255.0.0/27

# IP Addressing
ipv4_underlay_addressing:
  p2p_links_mtu: 1500
  p2p_links_ip_addressing: 'point-to-point'

# EVPN settings
evpn_vlan_aware_bundles: false