---
type: l3leaf

ansible_host: 192.168.0.20 # Update with your actual management IPs

# L3 Leaf settings
l3leaf:
  defaults:
    platform: vEOS-LAB
    virtual_router_mac_address: 00:1c:73:00:00:01
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
    bgp_defaults:
      - no bgp default ipv4-unicast
      - distance bgp 20 200 200
      - graceful-restart restart-time 300
      - graceful-restart
  node_groups:
    DC1_LEAFS:
      bgp_as: 65101
      loopback_ipv4_pool: 10.1.252.0/24
      vtep_loopback_ipv4_pool: 10.1.253.0/24
      uplink_ipv4_pool: 10.1.254.0/24
      uplink_interfaces: ['Ethernet3', 'Ethernet4', 'Ethernet5', 'Ethernet6']
      uplink_switches: ['dc1-spine1', 'dc1-spine1', 'dc1-spine2', 'dc1-spine2']
      mlag_interfaces: ['Ethernet1', 'Ethernet2']
      nodes:
        dc1-leaf1:
          id: 1
          mgmt_ip: 192.168.0.13/24
          uplink_switch_interfaces:
            - dc1-spine1:Ethernet3
            - dc1-spine1:Ethernet4
            - dc1-spine2:Ethernet3
            - dc1-spine2:Ethernet4
        dc1-leaf2:
          id: 2
          mgmt_ip: 192.168.0.14/24
          uplink_switch_interfaces:
            - dc1-spine1:Ethernet5
            - dc1-spine1:Ethernet6
            - dc1-spine2:Ethernet5
            - dc1-spine2:Ethernet6
    DC2_LEAFS:
      bgp_as: 65201
      loopback_ipv4_pool: 10.2.252.0/24
      vtep_loopback_ipv4_pool: 10.2.253.0/24
      uplink_ipv4_pool: 10.2.254.0/24
      uplink_interfaces: ['Ethernet3', 'Ethernet4', 'Ethernet5', 'Ethernet6']
      uplink_switches: ['dc2-spine1', 'dc2-spine1', 'dc2-spine2', 'dc2-spine2']
      mlag_interfaces: ['Ethernet1', 'Ethernet2']
      nodes:
        dc2-leaf1:
          id: 3
          mgmt_ip: 192.168.0.15/24
          uplink_switch_interfaces:
            - dc2-spine1:Ethernet3
            - dc2-spine1:Ethernet4
            - dc2-spine2:Ethernet3
            - dc2-spine2:Ethernet4
        dc2-leaf2:
          id: 4
          mgmt_ip: 192.168.0.16/24
          uplink_switch_interfaces:
            - dc2-spine1:Ethernet5
            - dc2-spine1:Ethernet6
            - dc2-spine2:Ethernet5
            - dc2-spine2:Ethernet6