---
- name: Build DC1 EVPN Fabric
  hosts: DC1
  gather_facts: false
  tasks:
    - name: Generate AVD structured configuration for DC1
      ansible.builtin.import_role:
        name: arista.avd.eos_designs
      vars:
        fabric_name: DC1

    - name: Generate device configuration and documentation for DC1
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen

- name: Build DC2 EVPN Fabric
  hosts: DC2
  gather_facts: false
  tasks:
    - name: Generate AVD structured configuration for DC2
      ansible.builtin.import_role:
        name: arista.avd.eos_designs
      vars:
        fabric_name: DC2

    - name: Generate device configuration and documentation for DC2
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen

- name: Configuration deployment with CVP
  hosts: CVP_cluster
  connection: local
  gather_facts: no
  vars:
    ansible_command_timeout: 1200
    ansible_connect_timeout: 600
    # CVP deployment variables
    container_root: 'DC_Fabric'
    configlets_prefix: 'AVD'
    cv_collection: v3
    device_filter: ['all']
  tasks:
    - name: Run CVP provisioning
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: '{{container_root}}'
        configlets_prefix: '{{configlets_prefix}}'
        cv_collection: '{{cv_collection}}'
        device_filter: '{{device_filter}}'
        execute_tasks: false
        cvp_topology_before_config: true